#!/usr/bin/env bash
set -e

function help()
{
    cat <<EOF
Manage packages of type container posted to ghcr.io
Usage:
  gh container <command>
Commands:
  list :     List packages of type container
  versions : List versions of a container package
EOF
}

HDR_ACCEPT='Accept: application/vnd.github+json'
HDR_API_VERSION='X-GitHub-Api-Version: 2022-11-28'

function list_packages()
{
    gh api -H "${HDR_ACCEPT}" -H "${HDR_API_VERSION}" \
        /user/packages?package_type=container \
        --jq '.[] | .name'
}

PARAMS=""
while [ $# -gt 0 ]; do
    key="$1"
    case ${key} in
        -h|--help)
            help
            exit 0
            ;;
        -v)
            echo verbose
            ;;
        *)
            PARAMS+=" $1"
            ;;
    esac
    shift
done
eval set -- "${PARAMS}"
ACTION="$1"

if [ "${ACTION}" == "list" ]; then
    list_packages
fi
